/**
 * Seed data for the initial catalogue.
 *
 * These 50 assets match the frontend's mock catalog verbatim so the
 * demo has continuity: the same ids, titles, tags, and picsum thumbnails.
 *
 * When we get real Cloudinary uploads, this seed still runs on a fresh
 * DB so a cold-boot demo (no user uploads yet) still shows a rich feed.
 */

export type SeedAssetType = 'PHOTO' | 'VIDEO' | 'GRAPHIC' | '3D';

export interface SeedAsset {
  id: string;
  title: string;
  displayTitle: string;
  type: SeedAssetType;
  format: string;
  sizeLabel: string;
  date: string;
  ownerLabel: string;
  visual: string;
  tags: string[];
  premium: boolean;
  likes: number;
  downloads: number;
}

export function seedImageUrl(id: string, w = 800, h = 600): string {
  return `https://picsum.photos/seed/kontaner-${id}/${w}/${h}`;
}

export const seedAssets: SeedAsset[] = [
  { id: 'kente-market-portrait', title: 'kente-market-portrait.jpg', displayTitle: 'Accra Makola Vendor', type: 'PHOTO', format: 'JPG', sizeLabel: '4.2 MB', date: 'Oct 12, 2023', ownerLabel: 'Verified Author', visual: 'visual-kente', tags: ['market woman', 'Accra', 'culture', 'Kente Fabric', 'Street Photography'], premium: false, likes: 1240, downloads: 412 },
  { id: 'kejetia-daily-life', title: 'Kejetia Daily Life', displayTitle: 'Kejetia Daily Life', type: 'PHOTO', format: 'RAW', sizeLabel: '28 MB', date: 'Oct 08, 2023', ownerLabel: 'Ghana Creative Hub', visual: 'visual-market', tags: ['market woman', 'Kumasi', 'daily life', 'portrait'], premium: true, likes: 980, downloads: 188 },
  { id: 'heritage-details-04', title: 'Heritage Details 04', displayTitle: 'Heritage Details 04', type: 'PHOTO', format: 'PNG', sizeLabel: '12 MB', date: 'Oct 05, 2023', ownerLabel: 'Studio Accra', visual: 'visual-portrait', tags: ['textiles', 'Kente', 'portrait', 'heritage'], premium: false, likes: 612, downloads: 219 },
  { id: 'sunrise-koforidua', title: 'Sunrise at Koforidua', displayTitle: 'Sunrise at Koforidua', type: 'PHOTO', format: 'JPG', sizeLabel: '5.1 MB', date: 'Sep 29, 2023', ownerLabel: 'Verified Author', visual: 'visual-village', tags: ['landscape', 'Ghana', 'community', 'sunrise'], premium: false, likes: 1503, downloads: 521 },
  { id: 'kente-pattern-v2', title: 'Kente_Pattern_v2.jpg', displayTitle: 'Kente Pattern v2', type: 'PHOTO', format: 'JPG', sizeLabel: '12.4 MB', date: 'Oct 12, 2023', ownerLabel: 'Verified Author', visual: 'visual-textile', tags: ['Textile', 'Pattern', 'Heritage', 'Ghanaian Market'], premium: true, likes: 2104, downloads: 743 },
  { id: 'accra-twilight', title: 'Accra_Twilight_4K.mp4', displayTitle: 'Accra Twilight 4K', type: 'VIDEO', format: 'MP4', sizeLabel: '245 MB', date: 'Oct 11, 2023', ownerLabel: 'Studio Accra', visual: 'visual-city', tags: ['Aerial', 'Urban', 'Cityscape', 'Accra'], premium: true, likes: 1842, downloads: 309 },
  { id: 'aburi-gardens', title: 'Aburi_Gardens_01.png', displayTitle: 'Aburi Gardens', type: 'PHOTO', format: 'PNG', sizeLabel: '8.2 MB', date: 'Oct 09, 2023', ownerLabel: 'Kontaner Original', visual: 'visual-palms', tags: ['Nature', 'Ghana', 'Travel', 'Landscape'], premium: false, likes: 794, downloads: 312 },
  { id: 'creative-abstract', title: 'Creative_Abstract_Illu.ai', displayTitle: 'Creative Abstract Illu', type: 'GRAPHIC', format: 'AI', sizeLabel: '4.5 MB', date: 'Oct 05, 2023', ownerLabel: 'Studio Accra', visual: 'visual-illustration', tags: ['Graphic', 'Vector', 'Art', 'Afrobeat'], premium: false, likes: 530, downloads: 198 },
  { id: 'market-vibrance', title: 'Market_Vibrance_Ref.jpg', displayTitle: 'Market Vibrance', type: 'PHOTO', format: 'JPG', sizeLabel: '15.1 MB', date: 'Oct 02, 2023', ownerLabel: 'Verified Author', visual: 'visual-baskets', tags: ['Culture', 'Market', 'Daily Life', 'Commerce'], premium: false, likes: 1102, downloads: 408 },
  { id: 'adinkra-sculpt', title: 'Adinkra_Sculpt_Gold.obj', displayTitle: 'Adinkra Sculpt Gold', type: '3D', format: 'OBJ', sizeLabel: '45.0 MB', date: 'Sep 28, 2023', ownerLabel: 'Kontaner Original', visual: 'visual-gold', tags: ['3D', 'Adinkra', 'Gold', 'Pattern'], premium: true, likes: 412, downloads: 91 },
  { id: 'cape-coast-castle', title: 'Cape_Coast_Castle_Dawn.jpg', displayTitle: 'Cape Coast Castle at Dawn', type: 'PHOTO', format: 'JPG', sizeLabel: '9.8 MB', date: 'Sep 25, 2023', ownerLabel: 'Verified Author', visual: 'visual-architecture', tags: ['Heritage', 'Architecture', 'History', 'Cape Coast'], premium: false, likes: 1631, downloads: 489 },
  { id: 'studio-portrait-amma', title: 'Studio_Portrait_Amma.jpg', displayTitle: 'Studio Portrait — Amma', type: 'PHOTO', format: 'JPG', sizeLabel: '6.4 MB', date: 'Sep 22, 2023', ownerLabel: 'Studio Accra', visual: 'visual-studio', tags: ['portrait', 'studio', 'fashion', 'editorial'], premium: true, likes: 1287, downloads: 264 },
  { id: 'jamestown-streetlife', title: 'Jamestown_Streetlife_03.jpg', displayTitle: 'Jamestown Streetlife', type: 'PHOTO', format: 'JPG', sizeLabel: '7.1 MB', date: 'Sep 19, 2023', ownerLabel: 'Ghana Creative Hub', visual: 'visual-city', tags: ['Street Photography', 'Accra', 'Daily Life', 'Urban'], premium: false, likes: 892, downloads: 342 },
  { id: 'kente-loom-closeup', title: 'Kente_Loom_Closeup.jpg', displayTitle: 'Kente Loom Closeup', type: 'PHOTO', format: 'JPG', sizeLabel: '11.2 MB', date: 'Sep 17, 2023', ownerLabel: 'Verified Author', visual: 'visual-textile', tags: ['Kente Fabric', 'craft', 'Bonwire', 'textile'], premium: false, likes: 1742, downloads: 612 },
  { id: 'afrobeat-poster', title: 'Afrobeat_Poster_01.ai', displayTitle: 'Afrobeat Poster', type: 'GRAPHIC', format: 'AI', sizeLabel: '5.2 MB', date: 'Sep 14, 2023', ownerLabel: 'Studio Accra', visual: 'visual-illustration', tags: ['Poster', 'Afrobeat', 'Music', 'Graphic Design'], premium: true, likes: 643, downloads: 121 },
  { id: 'volta-river-aerial', title: 'Volta_River_Aerial.mp4', displayTitle: 'Volta River Aerial', type: 'VIDEO', format: 'MP4', sizeLabel: '312 MB', date: 'Sep 11, 2023', ownerLabel: 'Kontaner Original', visual: 'visual-palms', tags: ['Aerial', 'Drone', 'Nature', 'Volta'], premium: true, likes: 1308, downloads: 174 },
  { id: 'osu-night-life', title: 'Osu_Night_Life.jpg', displayTitle: 'Osu Night Life', type: 'PHOTO', format: 'JPG', sizeLabel: '8.6 MB', date: 'Sep 09, 2023', ownerLabel: 'Ghana Creative Hub', visual: 'visual-city', tags: ['Night', 'Accra', 'Bokeh', 'Urban Life'], premium: false, likes: 1015, downloads: 388 },
  { id: 'fante-festival', title: 'Fante_Festival_Drums.jpg', displayTitle: 'Fante Festival Drums', type: 'PHOTO', format: 'JPG', sizeLabel: '13.4 MB', date: 'Sep 06, 2023', ownerLabel: 'Verified Author', visual: 'visual-portrait', tags: ['Festival', 'Culture', 'Drums', 'Fante'], premium: false, likes: 1422, downloads: 502 },
  { id: 'palm-grove-pattern', title: 'Palm_Grove_Pattern.png', displayTitle: 'Palm Grove Pattern', type: 'GRAPHIC', format: 'PNG', sizeLabel: '3.1 MB', date: 'Sep 03, 2023', ownerLabel: 'Studio Accra', visual: 'visual-palms', tags: ['Pattern', 'Tropical', 'Botanical', 'Repeat'], premium: true, likes: 738, downloads: 169 },
  { id: 'shea-butter-market', title: 'Shea_Butter_Market.jpg', displayTitle: 'Shea Butter Market', type: 'PHOTO', format: 'JPG', sizeLabel: '6.8 MB', date: 'Aug 30, 2023', ownerLabel: 'Kontaner Original', visual: 'visual-baskets', tags: ['Market', 'Commerce', 'Tamale', 'Northern Ghana'], premium: false, likes: 821, downloads: 287 },
  { id: 'lagos-meets-accra', title: 'Lagos_Meets_Accra.mp4', displayTitle: 'Lagos Meets Accra', type: 'VIDEO', format: 'MP4', sizeLabel: '198 MB', date: 'Aug 27, 2023', ownerLabel: 'Studio Accra', visual: 'visual-city', tags: ['Travel', 'West Africa', 'Documentary', 'Cinematic'], premium: true, likes: 1244, downloads: 211 },
  { id: 'adinkra-symbols-set', title: 'Adinkra_Symbols_Set.ai', displayTitle: 'Adinkra Symbols Set', type: 'GRAPHIC', format: 'AI', sizeLabel: '7.7 MB', date: 'Aug 25, 2023', ownerLabel: 'Ghana Creative Hub', visual: 'visual-illustration', tags: ['Adinkra', 'Symbols', 'Vector', 'Heritage'], premium: false, likes: 1576, downloads: 642 },
  { id: 'bonwire-weaver', title: 'Bonwire_Weaver_at_Work.jpg', displayTitle: 'Bonwire Weaver at Work', type: 'PHOTO', format: 'JPG', sizeLabel: '9.3 MB', date: 'Aug 22, 2023', ownerLabel: 'Verified Author', visual: 'visual-kente', tags: ['Kente', 'Weaving', 'Craftsmanship', 'Bonwire'], premium: true, likes: 1989, downloads: 538 },
  { id: 'urban-mural-jamestown', title: 'Urban_Mural_Jamestown.jpg', displayTitle: 'Urban Mural — Jamestown', type: 'PHOTO', format: 'JPG', sizeLabel: '10.5 MB', date: 'Aug 19, 2023', ownerLabel: 'Studio Accra', visual: 'visual-architecture', tags: ['Mural', 'Street Art', 'Accra', 'Color'], premium: false, likes: 994, downloads: 311 },
  { id: 'palm-wine-evening', title: 'Palm_Wine_Evening.jpg', displayTitle: 'Palm Wine Evening', type: 'PHOTO', format: 'JPG', sizeLabel: '7.9 MB', date: 'Aug 16, 2023', ownerLabel: 'Ghana Creative Hub', visual: 'visual-village', tags: ['Village', 'Evening', 'Tradition', 'Community'], premium: false, likes: 612, downloads: 178 },
  { id: 'highlife-album-cover', title: 'Highlife_Album_Cover.png', displayTitle: 'Highlife Album Cover', type: 'GRAPHIC', format: 'PNG', sizeLabel: '4.2 MB', date: 'Aug 13, 2023', ownerLabel: 'Kontaner Original', visual: 'visual-illustration', tags: ['Music', 'Album Art', 'Highlife', 'Vintage'], premium: true, likes: 433, downloads: 89 },
  { id: 'kakum-canopy', title: 'Kakum_Canopy_Walk.jpg', displayTitle: 'Kakum Canopy Walk', type: 'PHOTO', format: 'JPG', sizeLabel: '11.8 MB', date: 'Aug 10, 2023', ownerLabel: 'Verified Author', visual: 'visual-palms', tags: ['Forest', 'Travel', 'Adventure', 'Central Region'], premium: false, likes: 1387, downloads: 502 },
  { id: 'tro-tro-rush', title: 'Tro_Tro_Rush_Hour.jpg', displayTitle: 'Tro-Tro Rush Hour', type: 'PHOTO', format: 'JPG', sizeLabel: '8.1 MB', date: 'Aug 07, 2023', ownerLabel: 'Ghana Creative Hub', visual: 'visual-city', tags: ['Transport', 'Urban', 'Daily Life', 'Accra'], premium: false, likes: 944, downloads: 366 },
  { id: 'cocoa-harvest', title: 'Cocoa_Harvest_Closeup.jpg', displayTitle: 'Cocoa Harvest', type: 'PHOTO', format: 'JPG', sizeLabel: '14.0 MB', date: 'Aug 04, 2023', ownerLabel: 'Kontaner Original', visual: 'visual-gold', tags: ['Agriculture', 'Cocoa', 'Harvest', 'Western Region'], premium: true, likes: 1166, downloads: 281 },
  { id: 'fashion-week-runway', title: 'Fashion_Week_Runway.mp4', displayTitle: 'Accra Fashion Week Runway', type: 'VIDEO', format: 'MP4', sizeLabel: '420 MB', date: 'Aug 02, 2023', ownerLabel: 'Studio Accra', visual: 'visual-studio', tags: ['Fashion', 'Runway', 'Editorial', 'Accra'], premium: true, likes: 1721, downloads: 198 },
  { id: 'beach-football-labadi', title: 'Beach_Football_Labadi.jpg', displayTitle: 'Beach Football — Labadi', type: 'PHOTO', format: 'JPG', sizeLabel: '8.9 MB', date: 'Jul 30, 2023', ownerLabel: 'Verified Author', visual: 'visual-village', tags: ['Beach', 'Football', 'Labadi', 'Youth'], premium: false, likes: 1492, downloads: 587 },
  { id: 'gold-jewelry-macro', title: 'Gold_Jewelry_Macro.jpg', displayTitle: 'Gold Jewelry Macro', type: 'PHOTO', format: 'JPG', sizeLabel: '17.2 MB', date: 'Jul 27, 2023', ownerLabel: 'Kontaner Original', visual: 'visual-gold', tags: ['Gold', 'Jewelry', 'Macro', 'Craft'], premium: true, likes: 1033, downloads: 217 },
  { id: 'tema-port-dawn', title: 'Tema_Port_at_Dawn.jpg', displayTitle: 'Tema Port at Dawn', type: 'PHOTO', format: 'JPG', sizeLabel: '12.0 MB', date: 'Jul 24, 2023', ownerLabel: 'Studio Accra', visual: 'visual-architecture', tags: ['Port', 'Industrial', 'Dawn', 'Tema'], premium: false, likes: 712, downloads: 198 },
  { id: 'palm-pattern-vector', title: 'Palm_Pattern_Vector.ai', displayTitle: 'Palm Pattern Vector', type: 'GRAPHIC', format: 'AI', sizeLabel: '2.3 MB', date: 'Jul 21, 2023', ownerLabel: 'Ghana Creative Hub', visual: 'visual-palms', tags: ['Vector', 'Pattern', 'Botanical', 'Tropical'], premium: false, likes: 884, downloads: 351 },
  { id: 'fante-fisherman', title: 'Fante_Fisherman_Elmina.jpg', displayTitle: 'Fante Fisherman — Elmina', type: 'PHOTO', format: 'JPG', sizeLabel: '10.7 MB', date: 'Jul 18, 2023', ownerLabel: 'Verified Author', visual: 'visual-portrait', tags: ['Portrait', 'Fishing', 'Elmina', 'Documentary'], premium: true, likes: 1812, downloads: 412 },
  { id: 'kente-modern-fashion', title: 'Kente_Modern_Fashion.jpg', displayTitle: 'Kente Modern Fashion', type: 'PHOTO', format: 'JPG', sizeLabel: '9.4 MB', date: 'Jul 15, 2023', ownerLabel: 'Studio Accra', visual: 'visual-kente', tags: ['Fashion', 'Kente', 'Modern', 'Editorial'], premium: true, likes: 2143, downloads: 587 },
  { id: 'accra-skyline-vector', title: 'Accra_Skyline_Vector.ai', displayTitle: 'Accra Skyline Vector', type: 'GRAPHIC', format: 'AI', sizeLabel: '6.1 MB', date: 'Jul 12, 2023', ownerLabel: 'Kontaner Original', visual: 'visual-city', tags: ['Vector', 'Skyline', 'Accra', 'Illustration'], premium: false, likes: 521, downloads: 173 },
  { id: 'koforidua-flora', title: 'Koforidua_Flora_Macro.jpg', displayTitle: 'Koforidua Flora Macro', type: 'PHOTO', format: 'JPG', sizeLabel: '13.8 MB', date: 'Jul 09, 2023', ownerLabel: 'Ghana Creative Hub', visual: 'visual-palms', tags: ['Macro', 'Botanical', 'Flora', 'Eastern Region'], premium: false, likes: 638, downloads: 174 },
  { id: 'cultural-dance-3d', title: 'Cultural_Dance_3D.obj', displayTitle: 'Cultural Dance 3D', type: '3D', format: 'OBJ', sizeLabel: '58.0 MB', date: 'Jul 06, 2023', ownerLabel: 'Studio Accra', visual: 'visual-illustration', tags: ['3D', 'Dance', 'Culture', 'Sculpt'], premium: true, likes: 318, downloads: 64 },
  { id: 'sankofa-symbol-3d', title: 'Sankofa_Symbol_3D.obj', displayTitle: 'Sankofa Symbol 3D', type: '3D', format: 'OBJ', sizeLabel: '21.3 MB', date: 'Jul 03, 2023', ownerLabel: 'Kontaner Original', visual: 'visual-gold', tags: ['3D', 'Sankofa', 'Symbol', 'Heritage'], premium: false, likes: 472, downloads: 132 },
  { id: 'market-spices', title: 'Market_Spices_Closeup.jpg', displayTitle: 'Market Spices', type: 'PHOTO', format: 'JPG', sizeLabel: '11.1 MB', date: 'Jun 30, 2023', ownerLabel: 'Verified Author', visual: 'visual-baskets', tags: ['Spices', 'Market', 'Color', 'Commerce'], premium: false, likes: 1287, downloads: 471 },
  { id: 'mole-elephants', title: 'Mole_Elephants_Sunrise.mp4', displayTitle: 'Mole Elephants at Sunrise', type: 'VIDEO', format: 'MP4', sizeLabel: '378 MB', date: 'Jun 27, 2023', ownerLabel: 'Kontaner Original', visual: 'visual-village', tags: ['Wildlife', 'Elephants', 'Mole', 'Sunrise'], premium: true, likes: 2387, downloads: 412 },
  { id: 'editorial-textile-flatlay', title: 'Editorial_Textile_Flatlay.jpg', displayTitle: 'Editorial Textile Flatlay', type: 'PHOTO', format: 'JPG', sizeLabel: '14.6 MB', date: 'Jun 24, 2023', ownerLabel: 'Studio Accra', visual: 'visual-textile', tags: ['Editorial', 'Textile', 'Flatlay', 'Studio'], premium: true, likes: 819, downloads: 198 },
  { id: 'ghana-flag-typography', title: 'Ghana_Flag_Typography.ai', displayTitle: 'Ghana Flag Typography', type: 'GRAPHIC', format: 'AI', sizeLabel: '3.8 MB', date: 'Jun 21, 2023', ownerLabel: 'Ghana Creative Hub', visual: 'visual-illustration', tags: ['Typography', 'Flag', 'Patriotic', 'Vector'], premium: false, likes: 401, downloads: 122 },
  { id: 'church-stained-glass', title: 'Church_Stained_Glass.jpg', displayTitle: 'Church Stained Glass', type: 'PHOTO', format: 'JPG', sizeLabel: '9.2 MB', date: 'Jun 18, 2023', ownerLabel: 'Verified Author', visual: 'visual-architecture', tags: ['Architecture', 'Religion', 'Light', 'Heritage'], premium: false, likes: 712, downloads: 199 },
  { id: 'beach-sunset-cape', title: 'Beach_Sunset_Cape.jpg', displayTitle: 'Beach Sunset — Cape Coast', type: 'PHOTO', format: 'JPG', sizeLabel: '8.7 MB', date: 'Jun 15, 2023', ownerLabel: 'Ghana Creative Hub', visual: 'visual-village', tags: ['Beach', 'Sunset', 'Cape Coast', 'Travel'], premium: false, likes: 1872, downloads: 633 },
  { id: 'fashion-studio-portrait', title: 'Fashion_Studio_Portrait.jpg', displayTitle: 'Fashion Studio Portrait', type: 'PHOTO', format: 'JPG', sizeLabel: '12.3 MB', date: 'Jun 12, 2023', ownerLabel: 'Studio Accra', visual: 'visual-studio', tags: ['Fashion', 'Studio', 'Portrait', 'Editorial'], premium: true, likes: 1418, downloads: 312 },
  { id: 'aerial-volta-lake', title: 'Aerial_Volta_Lake.mp4', displayTitle: 'Aerial — Volta Lake', type: 'VIDEO', format: 'MP4', sizeLabel: '512 MB', date: 'Jun 09, 2023', ownerLabel: 'Kontaner Original', visual: 'visual-palms', tags: ['Aerial', 'Drone', 'Lake', 'Nature'], premium: true, likes: 1582, downloads: 244 },
  { id: 'bead-jewelry-3d', title: 'Bead_Jewelry_3D.obj', displayTitle: 'Bead Jewelry 3D', type: '3D', format: 'OBJ', sizeLabel: '34.2 MB', date: 'Jun 06, 2023', ownerLabel: 'Studio Accra', visual: 'visual-gold', tags: ['3D', 'Jewelry', 'Beads', 'Craft'], premium: false, likes: 281, downloads: 71 },
  { id: 'street-vendor-portrait', title: 'Street_Vendor_Portrait.jpg', displayTitle: 'Street Vendor Portrait', type: 'PHOTO', format: 'JPG', sizeLabel: '6.9 MB', date: 'Jun 03, 2023', ownerLabel: 'Verified Author', visual: 'visual-portrait', tags: ['Portrait', 'Vendor', 'Street', 'Daily Life'], premium: false, likes: 1342, downloads: 502 },
];
